version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - garbanzo-network
  mongo:
    image: mongo
    networks:
      - garbanzo-network

networks:
  garbanzo-network:
    driver: bridge
